image: python:3.12.4
services:
  - gcr.io/diamond-privreg/lims/sample-handling-db:v1.6.1
stages:
  - test
  - build

install-job:
  stage: test
  tags:
    - argus
  script:
    - pip install .[dev]

lint-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - tox -e mypy

integration-test-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - tox -e pytest
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml

build-image:
  stage: build
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  only:
    - tags
  variables:
    IMAGE_NAME: gcr.io/diamond-privreg/lims/sample-handling/backend:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --destination $IMAGE_NAME
