apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Scaup
  title: Scaup
  description: Application for declaring contents and building sample shipments
spec:
  owner: group:lims
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scaup-backend
  title: Scaup Backend
  description: >
    Scaup API
  links:
    - url: https://ebic-scaup.diamond.ac.uk/api/docs
      title: Live server API documentation
  tags:
    - python
    - ispyb
spec:
  type: service
  lifecycle: production
  owner: group:lims
  system: scaup
  providesApis:
    - scaup-api
  consumesApis:
    - microauth-api
    - expeye-core-api
    - sample-shipping-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: scaup-api
  description: >
    Scaup API
spec:
  type: openapi
  lifecycle: production
  owner: group:lims
  system: scaup
  definition:
    $text: https://ebic-scaup.diamond.ac.uk/api/openapi.json
