apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample-handling
  title: Sample Handling
  description: Application for declaring contents and building sample shipments
spec:
  owner: group:lims
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-handling-backend
  title: Sample Handling Backend
  description: >
    Sample Handling API
  links:
    - url: https://ebic-sample-handling.diamond.ac.uk/api/docs
      title: Live server API documentation
  tags:
    - python
    - ispyb
spec:
  type: service
  lifecycle: production
  owner: group:lims
  system: sample-handling
  providesApis:
    - sample-handling-api
  consumesApis:
    - microauth-api
    - expeye-sample-handling-api
    - expeye-core-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-handling-api
  description: >
    Sample Handling API
spec:
  type: openapi
  lifecycle: production
  owner: group:lims
  system: sample-handling
  definition:
    $text: https://ebic-sample-handling.diamond.ac.uk/api/openapi.json
