"""Set null on delete for parents

Revision ID: 10383934c70b
Revises: bd83f0b51afb
Create Date: 2023-09-06 09:19:47.346035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10383934c70b"
down_revision: Union[str, None] = "bd83f0b51afb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Container_ibfk_3", "Container", type_="foreignkey")
    op.drop_constraint("Container_ibfk_2", "Container", type_="foreignkey")
    op.create_foreign_key(
        None,
        "Container",
        "Container",
        ["parentId"],
        ["containerId"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "Container",
        "TopLevelContainer",
        ["topLevelContainerId"],
        ["topLevelContainerId"],
        ondelete="SET NULL",
    )
    op.drop_constraint("Sample_ibfk_2", "Sample", type_="foreignkey")
    op.create_foreign_key(
        None,
        "Sample",
        "Container",
        ["containerId"],
        ["containerId"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Sample", type_="foreignkey")
    op.create_foreign_key(
        "Sample_ibfk_2", "Sample", "Container", ["containerId"], ["containerId"]
    )
    op.drop_constraint(None, "Container", type_="foreignkey")
    op.drop_constraint(None, "Container", type_="foreignkey")
    op.create_foreign_key(
        "Container_ibfk_2",
        "Container",
        "TopLevelContainer",
        ["topLevelContainerId"],
        ["topLevelContainerId"],
    )
    op.create_foreign_key(
        "Container_ibfk_3", "Container", "Container", ["parentId"], ["containerId"]
    )
    # ### end Alembic commands ###
