"""add subType column

Revision ID: 223b22c06811
Revises: 2437fc6c6661
Create Date: 2024-08-08 16:15:20.343530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223b22c06811'
down_revision: Union[str, None] = '2437fc6c6661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('subType', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Container', 'subType')
    # ### end Alembic commands ###
