"""Add sample parent/child relationship

Revision ID: 297144dfe234
Revises: 7325165750bc
Create Date: 2025-03-13 11:02:07.757527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297144dfe234'
down_revision: Union[str, None] = '7325165750bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SampleParentChild',
    sa.Column('parentId', sa.Integer(), nullable=False, comment='Sample(s) from which the child(ren) was derived from'),
    sa.Column('childId', sa.Integer(), nullable=False, comment='Sample(s) derived from parent(s)'),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['childId'], ['Sample.sampleId'], ),
    sa.ForeignKeyConstraint(['parentId'], ['Sample.sampleId'], ),
    sa.PrimaryKeyConstraint('parentId', 'childId', name='parent_child_pk')
    )
    op.create_index(op.f('ix_SampleParentChild_childId'), 'SampleParentChild', ['childId'], unique=False)
    op.create_index(op.f('ix_SampleParentChild_parentId'), 'SampleParentChild', ['parentId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SampleParentChild_parentId'), table_name='SampleParentChild')
    op.drop_index(op.f('ix_SampleParentChild_childId'), table_name='SampleParentChild')
    op.drop_table('SampleParentChild')
    # ### end Alembic commands ###
