"""Barcode is nullable

Revision ID: 3475edcfb324
Revises: 5ebbd7c2b164
Create Date: 2023-11-15 08:54:12.991167

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3475edcfb324"
down_revision: Union[str, None] = "5ebbd7c2b164"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "TopLevelContainer",
        "barCode",
        existing_type=mysql.VARCHAR(length=20),
        nullable=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "TopLevelContainer",
        "barCode",
        existing_type=mysql.VARCHAR(length=20),
        nullable=False,
    )

    # ### end Alembic commands ###
