"""Add registeredContainer column

Revision ID: 4c06e878da70
Revises: 91465026b6f3
Create Date: 2024-01-05 10:39:59.296244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c06e878da70'
down_revision: Union[str, None] = '91465026b6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('registeredContainer', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_TopLevelContainer_topLevelContainerId'), 'TopLevelContainer', ['topLevelContainerId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TopLevelContainer_topLevelContainerId'), table_name='TopLevelContainer')
    op.drop_column('Container', 'registeredContainer')
    # ### end Alembic commands ###
