"""Make details column not mandatory

Revision ID: 5ebbd7c2b164
Revises: b74d7e02e702
Create Date: 2023-10-11 14:09:28.567025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5ebbd7c2b164"
down_revision: Union[str, None] = "b74d7e02e702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "TopLevelContainer",
        "details",
        existing_type=mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "TopLevelContainer",
        "details",
        existing_type=mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
        nullable=False,
    )
    # ### end Alembic commands ###
