"""Make barcode column string

Revision ID: 730f6f07da68
Revises: dea9c772d734
Create Date: 2025-07-17 15:50:30.406046

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '730f6f07da68'
down_revision: Union[str, None] = 'dea9c772d734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TopLevelContainer', 'barCode',
               existing_type=sa.UUID(),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TopLevelContainer', 'barCode',
               existing_type=sa.String(length=40),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
