"""Add comments column to sample table

Revision ID: 7712d39c0cdc
Revises: 10383934c70b
Create Date: 2023-10-09 15:50:23.139219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7712d39c0cdc'
down_revision: Union[str, None] = '10383934c70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sample', sa.Column('comments', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sample', 'comments')
    # ### end Alembic commands ###
