"""External ID is unique

Revision ID: 8ec104fbae2f
Revises: 3475edcfb324
Create Date: 2023-11-20 14:44:16.052424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec104fbae2f'
down_revision: Union[str, None] = '3475edcfb324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Container', ['externalId'])
    op.create_unique_constraint(None, 'Sample', ['externalId'])
    op.create_unique_constraint(None, 'Shipment', ['externalId'])
    op.create_unique_constraint(None, 'TopLevelContainer', ['externalId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TopLevelContainer', type_='unique')
    op.drop_constraint(None, 'Shipment', type_='unique')
    op.drop_constraint(None, 'Sample', type_='unique')
    op.drop_constraint(None, 'Container', type_='unique')
    # ### end Alembic commands ###
