"""Add shipmentRequest column

Revision ID: 91465026b6f3
Revises: 8ec104fbae2f
Create Date: 2023-12-06 09:09:49.073987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91465026b6f3'
down_revision: Union[str, None] = '8ec104fbae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment', sa.Column('shipmentRequest', sa.Integer(), nullable=True))
    op.add_column('Shipment', sa.Column('status', sa.String(length=25), nullable=True))
    op.drop_column('TopLevelContainer', 'status')
    op.drop_column('TopLevelContainer', 'labContact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TopLevelContainer', sa.Column('labContact', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('TopLevelContainer', sa.Column('status', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('Shipment', 'status')
    op.drop_column('Shipment', 'shipmentRequest')
    # ### end Alembic commands ###
