"""Add unique constraint to top level container names

Revision ID: b22d0b329bca
Revises: cff8953e4ffb
Create Date: 2024-05-16 11:29:36.368939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b22d0b329bca"
down_revision: Union[str, None] = "cff8953e4ffb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "TopLevelContainer", ["name", "shipmentId"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "TopLevelContainer", type_="unique")
    # ### end Alembic commands ###
