"""Add externalId column

Revision ID: b39d8fe01630
Revises: 
Create Date: 2023-08-23 09:32:23.077748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39d8fe01630'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('externalId', sa.Integer(), nullable=True))
    op.add_column('Sample', sa.Column('externalId', sa.Integer(), nullable=True))
    op.add_column('Shipment', sa.Column('externalId', sa.Integer(), nullable=True))
    op.add_column('TopLevelContainer', sa.Column('externalId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TopLevelContainer', 'externalId')
    op.drop_column('Shipment', 'externalId')
    op.drop_column('Sample', 'externalId')
    op.drop_column('Container', 'externalId')
    # ### end Alembic commands ###
