"""Add subLocation column

Revision ID: bc8b830b4e87
Revises: 223b22c06811
Create Date: 2024-08-23 13:05:45.469538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8b830b4e87'
down_revision: Union[str, None] = '223b22c06811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sample', sa.Column('subLocation', sa.SmallInteger(), nullable=True, comment='Additional location, such as cassette slot or multi-sample pin position'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sample', 'subLocation')
    # ### end Alembic commands ###
