"""Add location column to container table

Revision ID: bd83f0b51afb
Revises: b39d8fe01630
Create Date: 2023-09-05 16:52:41.685383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd83f0b51afb"
down_revision: Union[str, None] = "b39d8fe01630"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Container", sa.Column("location", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Container", "location")
    # ### end Alembic commands ###
