"""Add session type column

Revision ID: c5d0b0fbc1e4
Revises: 31b603858335
Create Date: 2026-04-07 16:29:53.655808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5d0b0fbc1e4"
down_revision: Union[str, None] = "31b603858335"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session_type = op.create_table(
        "SessionType",
        sa.Column("sessionTypeId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column(
            "sampleCapacity",
            sa.SmallInteger(),
            nullable=False,
            comment="Number of samples that can be loaded in a session of this type",
        ),
        sa.PrimaryKeyConstraint("sessionTypeId"),
    )
    op.bulk_insert(
        session_type,
        [
            {"sessionTypeId": 1, "name": "TEM", "sampleCapacity": 12},
            {"sessionTypeId": 2, "name": "Aquilos", "sampleCapacity": 2},
        ],
    )
    op.create_index(op.f("ix_SessionType_name"), "SessionType", ["name"], unique=True)
    op.create_index(
        op.f("ix_SessionType_sessionTypeId"),
        "SessionType",
        ["sessionTypeId"],
        unique=False,
    )
    op.add_column(
        "Shipment",
        sa.Column("sessionTypeId", sa.Integer(), server_default="1", nullable=False),
    )
    op.create_foreign_key(
        None, "Shipment", "SessionType", ["sessionTypeId"], ["sessionTypeId"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Shipment", type_="foreignkey")
    op.drop_column("Shipment", "sessionTypeId")
    op.drop_index(op.f("ix_SessionType_sessionTypeId"), table_name="SessionType")
    op.drop_index(op.f("ix_SessionType_name"), table_name="SessionType")
    op.drop_table("SessionType")
    # ### end Alembic commands ###
