"""Add visit number column

Revision ID: cff8953e4ffb
Revises: 1daa99b93377
Create Date: 2024-04-30 12:58:49.053434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cff8953e4ffb"
down_revision: Union[str, None] = "1daa99b93377"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Container",
        "externalId",
        existing_type=sa.INTEGER(),
        comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    op.alter_column(
        "Sample",
        "externalId",
        existing_type=sa.INTEGER(),
        comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    op.add_column(
        "Shipment", sa.Column("proposalCode", sa.String(length=2), nullable=False)
    )
    op.add_column("Shipment", sa.Column("proposalNumber", sa.Integer(), nullable=False))
    op.add_column("Shipment", sa.Column("visitNumber", sa.Integer(), nullable=False))
    op.alter_column(
        "Shipment",
        "externalId",
        existing_type=sa.INTEGER(),
        comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    op.drop_index("ix_Shipment_proposalReference", table_name="Shipment")
    op.create_index(
        op.f("ix_Shipment_proposalCode"), "Shipment", ["proposalCode"], unique=False
    )
    op.create_index(
        op.f("ix_Shipment_proposalNumber"), "Shipment", ["proposalNumber"], unique=False
    )
    op.create_index(
        op.f("ix_Shipment_visitNumber"), "Shipment", ["visitNumber"], unique=False
    )
    op.drop_column("Shipment", "proposalReference")
    op.alter_column(
        "TopLevelContainer",
        "externalId",
        existing_type=sa.INTEGER(),
        comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "TopLevelContainer",
        "externalId",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    op.add_column(
        "Shipment",
        sa.Column(
            "proposalReference",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_Shipment_visitNumber"), table_name="Shipment")
    op.drop_index(op.f("ix_Shipment_proposalNumber"), table_name="Shipment")
    op.drop_index(op.f("ix_Shipment_proposalCode"), table_name="Shipment")
    op.create_index(
        "ix_Shipment_proposalReference", "Shipment", ["proposalReference"], unique=False
    )
    op.alter_column(
        "Shipment",
        "externalId",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    op.drop_column("Shipment", "visitNumber")
    op.drop_column("Shipment", "proposalNumber")
    op.drop_column("Shipment", "proposalCode")
    op.alter_column(
        "Sample",
        "externalId",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    op.alter_column(
        "Container",
        "externalId",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Item ID in ISPyB",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
