"""Add lastStatusUpdate column

Revision ID: dea9c772d734
Revises: 297144dfe234
Create Date: 2025-06-04 09:21:34.341747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea9c772d734'
down_revision: Union[str, None] = '297144dfe234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment', sa.Column('lastStatusUpdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipment', 'lastStatusUpdate')
    # ### end Alembic commands ###
